Vrajs16/TaskAi

documents/edendubrovsky.md
Created readMe file in documents
=> ReadMe-EdenDubrovsky

web/src/pages/HomePage/HomePage.js
Added text and route to planner view
=> Updated Landing Page

api/db/migrations/20221115211923_tasks_by_user_id/migration.sql, api/db/schema.prisma, api/src/graphql/tasks.sdl.js, api/src/services/tasks/tasks.scenarios.js, api/src/services/tasks/tasks.test.js, web/src/components/Task/EditTaskCell/EditTaskCell.js, web/src/components/Task/NewTask/NewTask.js, web/src/components/Task/Task/Task.js, web/src/components/Task/TaskCell/TaskCell.js, web/src/components/Task/TaskForm/TaskForm.js, web/src/components/Task/Tasks/Tasks.js, web/src/components/Task/TasksCell/TasksCell.js, web/src/components/TaskView/TaskView.js
Added tasklist display inside tasks and a link and ability for people to make tasks.
=> Make tasks

documents/melvinacademia.md, web/src/components/Task/EditTaskCell/EditTaskCell.js, web/src/components/Task/Task/Task.js, web/src/components/Task/TaskCell/TaskCell.js, web/src/components/Task/TaskForm/TaskForm.js, web/src/components/Task/TasksCell/TasksCell.js, web/src/layouts/ScaffoldLayout/ScaffoldLayout.js, web/src/layouts/ScaffoldLayout/ScaffoldLayout.stories.js, web/src/pages/Task/TaskPage/TaskPage.js
Created task card to be used on single task viewing page. Changed task form appearance to match the task card more to be used on edit & new task pages. Changed scaffold layout to the main banner layout w/ edit & new task buttons for all task related pages.
=> Task card UI Changes

web/src/components/Task/TasksCell/TasksCell.js, web/src/components/TaskView/TaskView.js
Even though this is a commit on my machine, 90% of this was Alon, we just had to integrate it using my machine for technical reasons.
=> Working filterable tasks AFTER integrating Alons code

web/src/components/Task/TasksCell/TasksCell.js, web/src/components/TaskView/TaskView.js
=> Revert "Dev"

web/src/components/Task/TasksCell/TasksCell.js, web/src/components/TaskView/TaskView.js
Change so that tasks are shown where tasks need to be shown
=> Slight bug fix

web/src/components/Task/TasksCell/TasksCell.js, web/src/components/TaskView/TaskView.js
=> Revert "Revert "Dev""

documents/melvinacademia.md, web/src/components/Task/EditTaskCell/EditTaskCell.js, web/src/components/Task/NewTask/NewTask.js, web/src/components/Task/Task/Task.js, web/src/components/Task/TaskForm/TaskForm.js, web/src/components/Task/Tasks/Tasks.js, web/src/components/TaskView/TaskView.js, web/src/pages/Task/TaskPage/TaskPage.js, web/src/pages/Task/TasksPage/TasksPage.js
Update Task Card UI in Single Task View, Edit Task, New Task, and Task List pages
=> Task card melvin academia

documents/robertdiasio.md, web/src/components/Task/NewTask/NewTask.js, web/src/components/Task/TaskForm/TaskForm.js
Users can now only create tasks
The task defaults to userID of 1, to be changed when login api is working. The task when created redirects to the planner page.
=> Edited creating tasks

documents/edendubrovsky.md, web/src/layouts/Next.js, web/src/layouts/theme.js
Adding some files for chakra ui light and dark mode
=> Adding Setup for Chakra Dark Mode

web/src/pages/HomePage/HomePage.js, web/src/pages/HomePage/HomePage.test.js
Wrote unit tests for the home page and fixed a color issue
=> Test cases - HomePage

documents/edendubrovsky.md, web/src/layouts/BannerLayout/BannerLayout.test.js, web/src/pages/HomePage/HomePage.test.js, web/src/pages/LoginPage/LoginPage.test.js, web/src/pages/PlannerPage/PlannerPage.test.js
Adding unit tests and editing readme file
=> Unit Tests: Home, Banner, Login, Planner Pages

api/src/services/tasks/tasks.js, documents/mohamedrachid.md, web/src/layouts/BannerLayout/BannerLayout.js
Tasks query only grabs current user's tasks. Do not need to update code anywhere in the project, should work as is.
=> Tasks Query Filtering on Backend

web/src/Routes.js, web/src/pages/ProfilePage/ProfilePage.js
…e, made all user pages unreachable if you are not signed in
=> combined first and last name fields into full name on the profile page, made all user pages unreachable if you are not signed in

package.json, web/src/App.js, web/src/index.css, web/src/layouts/AuthLayout/AuthLayout.js, web/src/layouts/BannerLayout/BannerLayout.js, web/src/layouts/Next.js, web/src/pages/ForgotPasswordPage/ForgotPasswordPage.js, web/src/pages/LoginPage/LoginPage.js, web/src/pages/NotFoundPage/NotFoundPage.js, web/src/pages/ProfilePage/ProfilePage.js, web/src/pages/SignupPage/SignupPage.js, web/src/theme.js, yarn.lock
Micheal did this, however I had to create a new branch since for some reason it was overwriting other peoples work
=> Fixed some merge conflicts for micheals changes

documents/edendubrovsky.md, web/src/pages/HomePage/HomePage.js, web/src/pages/HomePage/HomePage.test.js
Removed Planner button on HomePage and added images with unit tests
=> HomePage Content and Tests

package.json, web/src/components/Task/Task/Task.js, web/src/components/Task/TaskForm/TaskForm.js, yarn.lock
TaskForm autosaves
Completed toggle added to form
IsAppointment field removed from TaskCard
Save button removed from form
=> TaskForm Autosave

web/src/pages/LoginPage/LoginPage.js
=> Empty Avatar Removed

documents/neerajseedani.md, web/src/pages/LoginPage/LoginPage.js, web/src/pages/SignupPage/SignupPage.js
=> Logo Fixed and Readme Added
